package lexer

enum class State {

    IDLE,
    POTENTIALLY_READING_COMMENT,
    READING_SINGLELINE_COMMENT,
    CLOSING_MULTILINE_COMMENT,
    READING_MULTILINE_COMMENT,
    BUILDING_CLASS_IDENTIFIER,
    BUILDING_IDENTIFIER_OR_KEYWORD,
    BUILDING_INTEGER_CONSTANT,
    BUILDING_CHAR_CONSTANT,
    BUILDING_SCAPED_CHAR_CONSTANT,
    CLOSING_CHAR_CONSTANT,
    BUILDING_STRING_CONSTANT,
    BUILDING_SCAPED_STRING_CONSTANT,
    BUILDING_OPERATOR

}