package lexer

enum class State {

    IDLE,
    POTENTIALLY_READING_COMMENT,
    READING_SINGLELINE_COMMENT,
    READING_MULTINE_COMMENT,
    BUILDING_IDENTIFIER_CLASS_IDENTIFIER,
    BUILDING_IDENTIFIER_OR_KEYWORD,
    BUILDING_INTEGER_CONSTANT,
    BUILDING_CHAR_CONSTANT,
    BUILDING_STRING_CONSTANT,
    BUILDING_OPERATOR

}